//%attributes = {}
If (Is macOS:C1572)
	
	If (Storage:C1525.ENVIRONMENT.DEVELOPER_DIR#Null:C1517)
		$DEVELOPER_DIR:=Storage:C1525.ENVIRONMENT.DEVELOPER_DIR
		SET ENVIRONMENT VARIABLE:C812("DEVELOPER_DIR";$DEVELOPER_DIR)
	End if 
	
End if 